use crate::ast::*;
use anyhow::Result;

/// Генерирует C++ (CODAL) из AST программы
pub fn generate(program: &Program) -> Result<String> {
    let mut gen = CodeGen::new();
    gen.emit_program(program)?;
    Ok(gen.output)
}

struct CodeGen {
    output: String,
    indent: usize,
}

impl CodeGen {
    fn new() -> Self {
        Self { output: String::new(), indent: 0 }
    }

    fn emit(&mut self, s: &str) {
        self.output.push_str(s);
    }

    fn line(&mut self, s: &str) {
        let indent = "    ".repeat(self.indent);
        self.output.push_str(&indent);
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn blank(&mut self) {
        self.output.push('\n');
    }

    // ── Программа ────────────────────────────────────────────

    fn emit_program(&mut self, program: &Program) -> Result<()> {
        // Шапка — стандартные инклуды CODAL
        self.emit("// Generated by j2bit — do not edit\n");
        self.emit("// https://github.com/user14923929/j2bit\n");
        self.blank();
        self.emit("#include \"MicroBit.h\"\n");
        self.blank();
        self.emit("MicroBit uBit;\n");
        self.blank();

        // Форвард-декларации
        for class in &program.classes {
            for method in &class.methods {
                if method.is_static {
                    self.emit(&format!(
                        "{} {}__{}({});\n",
                        emit_type(&method.return_ty),
                        class.name,
                        method.name,
                        emit_params(&method.params)
                    ));
                }
            }
        }
        self.blank();

        // Тела методов
        for class in &program.classes {
            for method in &class.methods {
                self.emit_method(class, method)?;
                self.blank();
            }
        }

        // Стандартная точка входа micro:bit
        self.emit("int main() {\n");
        self.emit("    uBit.init();\n");

        // Если есть класс с методом `main`, вызываем его
        let has_main = program.classes.iter().any(|c| {
            c.methods.iter().any(|m| m.name == "main" && m.is_static)
        });
        if has_main {
            // Ищем класс с main
            for class in &program.classes {
                if class.methods.iter().any(|m| m.name == "main" && m.is_static) {
                    self.emit(&format!("    {}__main();\n", class.name));
                }
            }
        }

        self.emit("    release_fiber();\n");
        self.emit("    return 0;\n");
        self.emit("}\n");
        Ok(())
    }

    fn emit_method(&mut self, class: &ClassDecl, method: &MethodDecl) -> Result<()> {
        let ret = emit_type(&method.return_ty);
        let params = emit_params(&method.params);
        let name = format!("{}_{}", class.name, method.name);

        self.emit(&format!("{ret} {name}({params}) {{\n"));
        self.indent += 1;
        for stmt in &method.body {
            self.emit_stmt(stmt)?;
        }
        self.indent -= 1;
        self.emit("}\n");
        Ok(())
    }

    // ── Statements ───────────────────────────────────────────

    fn emit_stmt(&mut self, stmt: &Stmt) -> Result<()> {
        match stmt {
            Stmt::VarDecl { ty, name, init } => {
                let ty_str = emit_type(ty);
                if let Some(expr) = init {
                    let val = self.emit_expr(expr)?;
                    self.line(&format!("{ty_str} {name} = {val};"));
                } else {
                    self.line(&format!("{ty_str} {name};"));
                }
            }

            Stmt::Expr(e) => {
                let s = self.emit_expr(e)?;
                self.line(&format!("{s};"));
            }

            Stmt::Return(val) => {
                if let Some(e) = val {
                    let s = self.emit_expr(e)?;
                    self.line(&format!("return {s};"));
                } else {
                    self.line("return;");
                }
            }

            Stmt::If { cond, then_body, else_body } => {
                let c = self.emit_expr(cond)?;
                self.line(&format!("if ({c}) {{"));
                self.indent += 1;
                for s in then_body { self.emit_stmt(s)?; }
                self.indent -= 1;
                if let Some(eb) = else_body {
                    self.line("} else {");
                    self.indent += 1;
                    for s in eb { self.emit_stmt(s)?; }
                    self.indent -= 1;
                }
                self.line("}");
            }

            Stmt::While { cond, body } => {
                let c = self.emit_expr(cond)?;
                self.line(&format!("while ({c}) {{"));
                self.indent += 1;
                for s in body { self.emit_stmt(s)?; }
                self.indent -= 1;
                self.line("}");
            }

            Stmt::For { init, cond, update, body } => {
                let init_str = match init {
                    Some(s) => {
                        // Временно буферизуем
                        let old = std::mem::take(&mut self.output);
                        self.emit_stmt(s)?;
                        let generated = std::mem::replace(&mut self.output, old);
                        // Убираем завершающий `;` и `\n` — for-loop сам добавит
                        generated.trim().trim_end_matches(';').trim().to_string()
                    }
                    None => String::new(),
                };
                let cond_str = match cond {
                    Some(e) => self.emit_expr(e)?,
                    None => String::new(),
                };
                let update_str = match update {
                    Some(e) => self.emit_expr(e)?,
                    None => String::new(),
                };
                self.line(&format!("for ({init_str}; {cond_str}; {update_str}) {{"));
                self.indent += 1;
                for s in body { self.emit_stmt(s)?; }
                self.indent -= 1;
                self.line("}");
            }
        }
        Ok(())
    }

    // ── Expressions ──────────────────────────────────────────

    fn emit_expr(&mut self, expr: &Expr) -> Result<String> {
        Ok(match expr {
            Expr::IntLit(n)   => n.to_string(),
            Expr::FloatLit(f) => format!("{f}f"),
            Expr::StrLit(s)   => format!("ManagedString(\"{s}\")"),
            Expr::BoolLit(b)  => if *b { "true".into() } else { "false".into() },
            Expr::Ident(n)    => n.clone(),

            Expr::Assign { target, value } => {
                let t = self.emit_expr(target)?;
                let v = self.emit_expr(value)?;
                format!("{t} = {v}")
            }

            Expr::BinOp { op, lhs, rhs } => {
                let l = self.emit_expr(lhs)?;
                let r = self.emit_expr(rhs)?;
                let op_str = match op {
                    BinOp::Add   => "+",
                    BinOp::Sub   => "-",
                    BinOp::Mul   => "*",
                    BinOp::Div   => "/",
                    BinOp::Mod   => "%",
                    BinOp::Eq    => "==",
                    BinOp::NotEq => "!=",
                    BinOp::Lt    => "<",
                    BinOp::LtEq  => "<=",
                    BinOp::Gt    => ">",
                    BinOp::GtEq  => ">=",
                    BinOp::And   => "&&",
                    BinOp::Or    => "||",
                };
                format!("({l} {op_str} {r})")
            }

            Expr::UnaryOp { op, expr } => {
                let e = self.emit_expr(expr)?;
                match op {
                    UnaryOp::Neg => format!("(-{e})"),
                    UnaryOp::Not => format!("(!{e})"),
                }
            }

            Expr::FieldAccess { object, field } => {
                let obj = self.emit_expr(object)?;
                format!("{obj}.{field}")
            }

            Expr::MethodCall { object, method, args } => {
                map_method_call(self, object, method, args)?
            }

            Expr::StaticCall { class, method, args } => {
                map_static_call(self, class, method, args)?
            }

            Expr::New { class, args } => {
                let args_str = self.emit_args(args)?;
                format!("{class}({args_str})")
            }
        })
    }

    fn emit_args(&mut self, args: &[Expr]) -> Result<String> {
        let mut parts = Vec::new();
        for a in args {
            parts.push(self.emit_expr(a)?);
        }
        Ok(parts.join(", "))
    }
}

// ── Маппинг Java API → CODAL API ────────────────────────────

/// Метод на объекте: obj.method(args)
fn map_method_call(gen: &mut CodeGen, object: &Expr, method: &str, args: &[Expr]) -> Result<String> {
    // Спецобработка для микробитовых объектов
    if let Expr::Ident(obj_name) = object {
        let codal = match (obj_name.as_str(), method) {
            // display.show("hello") → uBit.display.scroll("hello")
            ("display", "show")   => {
                let a = gen.emit_args(args)?;
                return Ok(format!("uBit.display.scroll({a})"));
            }
            ("display", "print")  => {
                let a = gen.emit_args(args)?;
                return Ok(format!("uBit.display.print({a})"));
            }
            ("display", "clear")  => return Ok("uBit.display.clear()".into()),
            ("display", "enable") => return Ok("uBit.display.enable(true)".into()),

            // buttons
            ("buttonA", "isPressed") => return Ok("uBit.buttonA.isPressed()".into()),
            ("buttonB", "isPressed") => return Ok("uBit.buttonB.isPressed()".into()),

            // sleep → fiber_sleep
            ("basic", "pause")    => {
                let a = gen.emit_args(args)?;
                return Ok(format!("fiber_sleep({a})"));
            }

            // serial
            ("serial", "println") => {
                let a = gen.emit_args(args)?;
                return Ok(format!("uBit.serial.send({a})"));
            }

            _ => None::<&str>,
        };
        if let Some(c) = codal {
            return Ok(c.into());
        }
    }

    // Обычный вызов
    let obj_str = gen.emit_expr(object)?;
    let args_str = gen.emit_args(args)?;
    Ok(format!("{obj_str}.{method}({args_str})"))
}

/// Статический вызов: ClassName.method(args)
fn map_static_call(gen: &mut CodeGen, class: &str, method: &str, args: &[Expr]) -> Result<String> {
    match (class, method) {
        // Math
        ("Math", "abs")   => { let a = gen.emit_args(args)?; Ok(format!("abs({a})")) }
        ("Math", "max")   => { let a = gen.emit_args(args)?; Ok(format!("max({a})")) }
        ("Math", "min")   => { let a = gen.emit_args(args)?; Ok(format!("min({a})")) }
        ("Math", "sqrt")  => { let a = gen.emit_args(args)?; Ok(format!("sqrtf({a})")) }
        ("Math", "random")=> { let a = gen.emit_args(args)?; Ok(format!("uBit.random({a})")) }

        // System.out.println → serial
        ("System", _) if method.starts_with("out") => {
            let a = gen.emit_args(args)?;
            Ok(format!("uBit.serial.send(ManagedString({a}))"))
        }

        // micro:bit display API (вызывается как StaticCall display.show(...))
        ("display", "show")    => { let a = gen.emit_args(args)?; Ok(format!("uBit.display.scroll({a})")) }
        ("display", "print")   => { let a = gen.emit_args(args)?; Ok(format!("uBit.display.print({a})")) }
        ("display", "clear")   => Ok("uBit.display.clear()".into()),
        ("display", "enable")  => Ok("uBit.display.enable(true)".into()),

        // micro:bit buttons
        ("buttonA", "isPressed") => Ok("uBit.buttonA.isPressed()".into()),
        ("buttonB", "isPressed") => Ok("uBit.buttonB.isPressed()".into()),

        // basic.pause → fiber_sleep
        ("basic", "pause")     => { let a = gen.emit_args(args)?; Ok(format!("fiber_sleep({a})")) }

        // serial
        ("serial", "println")  => { let a = gen.emit_args(args)?; Ok(format!("uBit.serial.send({a})")) }

        // Всё остальное — прямой вызов
        _ => {
            let a = gen.emit_args(args)?;
            Ok(format!("{class}__{method}({a})"))
        }
    }
}

// ── Helpers ─────────────────────────────────────────────────

fn emit_type(ty: &Type) -> String {
    match ty {
        Type::Void         => "void".into(),
        Type::Int          => "int".into(),
        Type::Float        => "float".into(),
        Type::Bool         => "bool".into(),
        Type::Str          => "ManagedString".into(),
        Type::Array(inner) => format!("{}*", emit_type(inner)),
        Type::Named(n)     => n.clone(),
    }
}

fn emit_params(params: &[Param]) -> String {
    params
        .iter()
        .map(|p| format!("{} {}", emit_type(&p.ty), p.name))
        .collect::<Vec<_>>()
        .join(", ")
}
